const CART = {
  ADD_CART: 'ADD_CART',
  REMOVE_CART: 'REMOVE_CART',
  INCREASE_CART: 'INCREASE_CART',
  DECREASE_CART: 'DECREASE_CART',
  CREATSE_USER_CART_PENDING: 'CREATSE_USER_CART_PENDING',
  CREATSE_USER_CART_SUCCESS: 'CREATSE_USER_CART_SUCCESS',
  CREATSE_USER_CART_FAILURE: 'CREATSE_USER_CART_FAILURE',
  GET_USER_CART_PENDING: 'GET_USER_CART_PENDING',
  GET_USER_CART_SUCCESS: 'GET_USER_CART_SUCCESS',
  GET_USER_CART_FAILURE: 'GET_USER_CART_FAILURE',
  UPDATE_USER_CART_PENDING: 'UPDATE_USER_CART_PENDING',
  UPDATE_USER_CART_SUCCESS: 'UPDATE_USER_CART_SUCCESS',
  UPDATE_USER_CART_FAILURE: 'UPDATE_USER_CART_FAILURE',
};

export default CART;
