const CHARACTERS = {
  FETCH_CHARACTERS_PENDING: 'FETCH_CHARACTERS_PENDING',
  FETCH_CHARACTERS_SUCCESS: 'FETCH_CHARACTERS_SUCCESS',
  FETCH_CHARACTERS_FAILURE: 'FETCH_CHARACTERS_FAILURE',
};

export default CHARACTERS;
